project:
  type: website
  output-dir: docs

website:
  title: "Erika Egg's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
     - mystyles.scss
    mainfont: BIZ UDPMincho
    #css: styles.css
    toc: true

editor: visual

